# ===============================================
#           RAID SHOP - CONFIGURAZIONE
# ===============================================

# Nomi delle GUI del negozio
GUI:
  generale: "&l&aNegozio Generale"
  libri: "&l&bNegozio Incantesimi"
  pozioni: "&l&dNegozio Pozioni"
  armor: "&l&cNegozio Armature"
  ingredienti: "&l&3Ingredienti Pozioni"
  shop: "&l&eNegozio Principale"

# ===============================================
#                   PREZZI OGGETTI
# ===============================================

prices:
  # Sezione Generale
  generale:
    # Armi
    diamond_sword: 15000
    iron_sword: 11000
    diamond_axe: 9000
    iron_axe: 8000
    crossbow: 20000
    trident: 100000
    bow: 20000

    # Cibo
    cooked_beef: 450.0
    bread: 240.0
    golden_apple: 3600.0

    # Munizioni
    arrow: 150
    spectral_arrow: 300
    firework_rocket: 600

    # Oggetti preziosi
    diamond: 2400
    experience_bottle: 600.0

  # Sezione Pozioni
  pozioni:
    strength: 4200.0
    speed: 3600.0
    jump_boost: 3000.0
    resistance: 5400.0
    instant_health: 4800.0
    fire_resistance: 4500.0
    absorption: 5100.0
    water_breathing: 3900.0
    slow_falling: 3300.0

    # Pozioni Splash
    splash_instant_health: 6000.0
    splash_strength: 5400.0
    splash_speed: 4800.0

    # Pozioni Negative
    weakness: 2400.0
    splash_weakness: 3600.0
    slowness: 2700.0
    splash_slowness: 3900.0

# Sezione Libri Incantati - CORRETTA INDENTAZIONE
libri:
  protection: 21600.0
  sharpness: 18000.0
  unbreaking: 26400.0
  power: 19200.0
  sweeping_edge: 20400.0
  aqua_affinity: 16800.0
  respiration: 15600.0
  punch: 18000.0
  flame: 21600.0

# Sezione Armature
armor:
  iron:
    iron_helmet: 9600.0
    iron_chestplate: 14400.0
    iron_leggings: 12000.0
    iron_boots: 7200.0
    iron_set: 36000.0

  diamond:
    diamond_helmet: 28800.0
    diamond_chestplate: 43200.0
    diamond_leggings: 36000.0
    diamond_boots: 21600.0
    diamond_set: 108000.0

# Sezione Ingredienti Pozioni
ingredienti:
  # Ingredienti base
  potion: 600.0
  blaze_powder: 1200.0
  nether_wart: 1500.0

  # Ingredienti comuni
  spider_eye: 1050.0
  fermented_spider_eye: 1800.0
  sugar: 750.0
  glistering_melon_slice: 2400.0
  golden_carrot: 2100.0
  pufferfish: 1950.0
  magma_cream: 2700.0

  # Ingredienti avanzati
  ghast_tear: 4500.0
  redstone: 900.0
  gunpowder: 1350.0
  glowstone_dust: 1650.0
  ender_pearl: 3600.0
  nautilus_shell: 3000.0
  phantom_membrane: 2400.0

# Configurazione Fix GUI
FixGUI:
  # Nome della GUI di riparazione
  name: "&l&6Riparazione Oggetti"

  # Dimensione dell'inventario (deve essere multiplo di 9: 9, 18, 27, 36, 45, 54)
  size: 27

  # Prezzo per riparare tutti gli oggetti
  price: 5000

  # Configurazione incudine
  anvil:
    name: "&6&lRipara Tutto"
    position: 13  # Posizione dell'incudine nella GUI (0-26 per size 27)
    lore:
      line1: "&7Clicca per riparare tutti"
      line2: "&7i tuoi oggetti danneggiati"
      line3: "&ePrezzo: &a€"  # Il prezzo viene aggiunto automaticamente

  # Configurazione vetri decorativi
  glass:
    name: "&7"
    color: 7  # Colore del vetro (0-15, vedi: https://minecraft.wiki/w/Dye#Data_values)

  # Posizione del portafoglio
  wallet:
    position: 4  # Posizione del portafoglio nella GUI

  # Impostazioni varie
  prevent-anvil-pickup: true  # Previene il pickup di incudini nel mondo

  # Configurazione suoni
  sounds:
    enabled: true  # Abilita/disabilita i suoni della FixGUI

  # Messaggi della FixGUI
  messages:
    success: "&a✓ Tutti i tuoi oggetti sono stati riparati!"
    no-money: "&c✗ Non hai abbastanza soldi per riparare gli oggetti!"

# Messaggi generali
messages:
  no-permission: "&cNon hai il permesso per fare questo"
  usage-shop: "&cComando errato. &eUtilizzo: &f/shopraid"
  usage-npc: "&cComando errato. &eUtilizzo: &f/setnpcshop &b<nick_skin>"
  usage-fix: "&cComando errato. &eUtilizzo: &f/fix"
  usage-reload: "&cComando errato. &eUtilizzo: &f/raidshop reload"
  config-reloaded: "&aConfigurazione ricaricata con successo!"

# Configurazione NPC
NPC:
  shop-name: "&l&6Negozio"