GUI:
  generale: "&l&aNegozio Generale"
  libri: "&l&bNegozio Libri"
  pozioni: "&l&dNegozio Pozioni"
  shop: "&l&eNegozio Principale"

messages:
  no-permission: "&cNon hai il permesso per fare questo"
  usage-shop: "&cComando errato. &eUtilizzo: &f/shopraid"
  usage-npc: "&cComando errato. &eUtilizzo: &f/setnpcshop &b<nick_skin>"


NPC:
  shop-name: "&l&6Negozio"