# ===============================================
#           RAID SHOP - CONFIGURAZIONE
# ===============================================

# Nomi delle GUI del negozio
GUI:
  generale: "&l&aNegozio Generale"
  libri: "&l&bNegozio Incantesimi"
  pozioni: "&l&dNegozio Pozioni"
  armor: "&l&cNegozio Armature"
  ingredienti: "&l&3Ingredienti Pozioni"
  shop: "&l&eNegozio Principale"

# ===============================================
#                   PREZZI OGGETTI
# ===============================================

prices:
  # Sezione Generale
  generale:
    # Armi
    diamond_sword: 1500.0
    iron_sword: 800.0
    diamond_axe: 1400.0
    iron_axe: 700.0
    crossbow: 900.0
    trident: 2500.0
    bow: 600.0

    # Cibo
    cooked_beef: 150.0
    bread: 80.0
    golden_apple: 1200.0

    # Munizioni
    arrow: 300.0
    spectral_arrow: 500.0
    firework_rocket: 400.0

    # Oggetti preziosi
    diamond: 2000.0
    experience_bottle: 600.0

  # Sezione Pozioni
  pozioni:
    strength: 1400.0
    speed: 1200.0
    jump_boost: 1000.0
    resistance: 1800.0
    instant_health: 1600.0
    fire_resistance: 1500.0
    absorption: 1700.0
    water_breathing: 1300.0
    slow_falling: 1100.0

    # Pozioni Splash
    splash_instant_health: 2000.0
    splash_strength: 1800.0
    splash_speed: 1600.0

    # Pozioni Negative
    weakness: 800.0
    splash_weakness: 1200.0
    slowness: 900.0
    splash_slowness: 1300.0

  # Sezione Libri Incantati
  libri:
    protection: 1800.0
    sharpness: 1500.0
    unbreaking: 2200.0
    power: 1600.0
    sweeping_edge: 1700.0
    aqua_affinity: 1400.0
    respiration: 1300.0
    punch: 1500.0
    flame: 1800.0

  # Sezione Armature
  armor:
    # Ferro
    iron_helmet: 800.0
    iron_chestplate: 1200.0
    iron_leggings: 1000.0
    iron_boots: 600.0
    iron_set: 3000.0

    # Diamante
    diamond_helmet: 2400.0
    diamond_chestplate: 3600.0
    diamond_leggings: 3000.0
    diamond_boots: 1800.0
    diamond_set: 9000.0

  # Sezione Ingredienti Pozioni
  ingredienti:
    # Ingredienti base
    potion: 200.0
    blaze_powder: 400.0
    nether_wart: 500.0

    # Ingredienti comuni
    spider_eye: 350.0
    fermented_spider_eye: 600.0
    sugar: 250.0
    glistering_melon_slice: 800.0
    golden_carrot: 700.0
    pufferfish: 650.0
    magma_cream: 900.0

    # Ingredienti avanzati
    ghast_tear: 1500.0
    redstone: 300.0
    gunpowder: 450.0
    glowstone_dust: 550.0
    ender_pearl: 1200.0
    nautilus_shell: 1000.0
    phantom_membrane: 800.0

# Configurazione Fix GUI
FixGUI:
  # Nome della GUI di riparazione
  name: "&l&6Riparazione Oggetti"

  # Dimensione dell'inventario (deve essere multiplo di 9: 9, 18, 27, 36, 45, 54)
  size: 27

  # Prezzo per riparare tutti gli oggetti
  price: 1000.0

  # Configurazione incudine
  anvil:
    name: "&6&lRipara Tutto"
    position: 13  # Posizione dell'incudine nella GUI (0-26 per size 27)
    lore:
      line1: "&7Clicca per riparare tutti"
      line2: "&7i tuoi oggetti danneggiati"
      line3: "&ePrezzo: &a€"  # Il prezzo viene aggiunto automaticamente

  # Configurazione vetri decorativi
  glass:
    name: "&7"
    color: 7  # Colore del vetro (0-15, vedi: https://minecraft.wiki/w/Dye#Data_values)

  # Posizione del portafoglio
  wallet:
    position: 4  # Posizione del portafoglio nella GUI

  # Impostazioni varie
  prevent-anvil-pickup: true  # Previene il pickup di incudini nel mondo

  # Configurazione suoni
  sounds:
    enabled: true  # Abilita/disabilita i suoni della FixGUI

  # Messaggi della FixGUI
  messages:
    success: "&a✓ Tutti i tuoi oggetti sono stati riparati!"
    no-money: "&c✗ Non hai abbastanza soldi per riparare gli oggetti!"

# Messaggi generali
messages:
  no-permission: "&cNon hai il permesso per fare questo"
  usage-shop: "&cComando errato. &eUtilizzo: &f/shopraid"
  usage-npc: "&cComando errato. &eUtilizzo: &f/setnpcshop &b<nick_skin>"
  usage-fix: "&cComando errato. &eUtilizzo: &f/fix"
  usage-reload: "&cComando errato. &eUtilizzo: &f/raidshop reload"
  config-reloaded: "&aConfigurazione ricaricata con successo!"

# Configurazione NPC
NPC:
  shop-name: "&l&6Negozio"