name: RaidShop
version: '1.1'
main: it.samuconfaa.raidShop.RaidShop
api-version: '1.21'
authors: [ samuconfaa ]
description: A complete shop system for Minecraft servers with repair functionality.
depend: [Vault]
softdepend: [Citizens]

commands:
  shopraid:
    description: Opens the shop GUI.
    usage: /<command>
    permission: raidshop.openshop
    permission-message: ${messages.no-permission}
  setnpcshop:
    description: Creates a shop NPC.
    usage: /<command> [skin_name]
    permission: raidshop.setnpc
    permission-message: ${messages.no-permission}
  fix:
    description: Opens the repair GUI to fix all your items.
    usage: /<command>
    permission: raidshop.fix
    permission-message: ${messages.no-permission}
  raidshop:
    description: Main RaidShop command for administration.
    usage: /<command> reload
    permission: raidshop.reload
    permission-message: ${messages.no-permission}

permissions:
  raidshop.*:
    description: Gives access to all RaidShop features.
    default: op
    children:
      raidshop.openshop: true
      raidshop.setnpc: true
      raidshop.fix: true
      raidshop.reload: true
  raidshop.openshop:
    description: Allows a player to open the shop with the command.
    default: true
  raidshop.setnpc:
    description: Allows a player to create a shop NPC.
    default: op
  raidshop.fix:
    description: Allows a player to use the repair functionality.
    default: true
  raidshop.reload:
    description: Allows a player to reload the RaidShop configuration.
    default: op